"""upgrade documents with doc_key checksum soft_delete and audit ip

Revision ID: 18278accfa61
Revises: 032edfe93de9
Create Date: 2026-02-20 13:39:39.654759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18278accfa61'
down_revision: Union[str, Sequence[str], None] = '032edfe93de9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_events', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.alter_column('audit_events', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_timestamp'), 'audit_events', ['timestamp'], unique=False)

    # Add doc_key as NULLABLE first
    op.add_column('documents', sa.Column('doc_key', sa.String(length=64), nullable=True))
    # Backfill existing rows with a unique key
    op.execute("UPDATE documents SET doc_key = SUBSTR(MD5(CAST(id AS TEXT)), 1, 16) WHERE doc_key IS NULL")
    # Now make it NOT NULL
    op.alter_column('documents', 'doc_key', nullable=False)

    op.add_column('documents', sa.Column('file_size', sa.BigInteger(), nullable=True))
    op.add_column('documents', sa.Column('is_latest', sa.Boolean(), nullable=True))
    # Backfill is_latest for existing rows
    op.execute("UPDATE documents SET is_latest = TRUE WHERE is_latest IS NULL")
    op.add_column('documents', sa.Column('checksum', sa.String(length=64), nullable=True))
    op.add_column('documents', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # Backfill is_deleted for existing rows
    op.execute("UPDATE documents SET is_deleted = FALSE WHERE is_deleted IS NULL")
    op.add_column('documents', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.alter_column('documents', 'file_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.create_index(op.f('ix_documents_doc_key'), 'documents', ['doc_key'], unique=False)
    op.create_foreign_key(None, 'documents', 'users', ['deleted_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_doc_key'), table_name='documents')
    op.alter_column('documents', 'file_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('documents', 'deleted_by')
    op.drop_column('documents', 'deleted_at')
    op.drop_column('documents', 'is_deleted')
    op.drop_column('documents', 'checksum')
    op.drop_column('documents', 'is_latest')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'doc_key')
    op.drop_index(op.f('ix_audit_events_timestamp'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.alter_column('audit_events', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('audit_events', 'ip_address')
    # ### end Alembic commands ###
