"""add refresh_tokens user_lock doc_lock storage_provider

Revision ID: 7b97afb7589d
Revises: 18278accfa61
Create Date: 2026-02-20 13:49:34.613119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b97afb7589d'
down_revision: Union[str, Sequence[str], None] = '18278accfa61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('storage_provider', sa.String(length=20), nullable=True))
    op.add_column('documents', sa.Column('is_locked', sa.Boolean(), nullable=True))
    op.add_column('documents', sa.Column('locked_by', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('locked_at', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('lock_reason', sa.String(length=500), nullable=True))
    op.create_foreign_key(None, 'documents', 'users', ['locked_by'], ['id'])
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'is_active')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'lock_reason')
    op.drop_column('documents', 'locked_at')
    op.drop_column('documents', 'locked_by')
    op.drop_column('documents', 'is_locked')
    op.drop_column('documents', 'storage_provider')
    # ### end Alembic commands ###
